services:
  app:
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - Name=Fady
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=postgres